# General settings for conditional MIS training

name: 'mis_conditional_gin'
use_conditional: True
wandb: 'disabled'
gpus: 1

resume: null
test_only: null
guidance_path: null

check_val_every_n_epochs: 5
sample_every_val: 4
val_check_interval: null

samples_to_generate: 4
samples_to_save: 4
chains_to_save: 0
log_every_steps: 50
number_chain_steps: 50

final_model_samples_to_generate: 100
final_model_samples_to_save: 100
final_model_chains_to_save: 0

evaluate_all_checkpoints: False
