type: discrete
use_persist_homo: true
extra_features: null
transition: 'uniform'
model: 'graph_tf'
diffusion_steps: 1000
diffusion_noise_schedule: 'cosine'
n_layers: 3

hidden_mlp_dims: {'X': 16, 'E': 16, 'y': 16}
hidden_dims: {'dx': 16, 'de': 16, 'dy': 16, 'n_head': 2, 'dim_ffX': 16, 'dim_ffE': 16, 'dim_ffy': 16}

lambda_train: [5, 0]
