defaults:
    - _self_
    - general: general_default_mis_conditional
    - model: discrete_mis_conditional
    - train: train_default_mis
    - dataset: mis

hydra:
  job:
    chdir: True
  run:
    dir: ../outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${general.name}
